### ISSUE TITLE
Please add a setup.py and uplaod to PyPI

### ISSUE THREAD

**Issue by htgoebel** [Yoriz/y_mvc#1]
As you are promiting ths framework to be used by your WxPython-Downloader. I'd appreciate being able to install this package like a fine Python package. So please add a setup.py and consider uploading the package to PyPI. Thanks.

**Comment by Yoriz** [comment]
At this point its not something i know how to do

**Comment by htgoebel** [comment]
To be frank: Closing this just because "At this point" do dn't know is, well, lame. You did not even ask how this could be done.

It is darn easy: https://packaging.python.org/tutorials/packaging-projects/
